from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.8.0")

configfile: "config.yaml"

##### load rules #####
include: "rules/common.smk"
include: "rules/qc.smk"