from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.8.0")

configfile: "config.yaml"

##### load rules #####
include: "rules/nano_dehost.smk"
include: "rules/read_qc.smk"
include: "rules/preassembly.smk"
include: "rules/binning.smk"

